### ISSUE TITLE
Remove Hotseat

### ISSUE THREAD

**Issue by yudimf** [klinker24/launcher3#4]
I want to remove hotseat (app dock) in homescreen view, i was trying to edit launcher.xml, launcher.java, hotseat.xml, hotseat.java, but nothing changed. do u have any idea ??

**Comment by klinker24** [comment]
I am not sure it makes sense to remove the dock with the latest version of Launcher3. The app drawer relies heavily on it. 

I did have an option for this in older versions of Blur, if you follow this option, it should take you to the spots that you will need to change: https://github.com/klinker24/Android-Blur-Launcher/blob/master/app/src/main/java/xyz/klinker/blur/addons/settings/AppSettings.java#L55

The option is no longer visible in Blur's settings though, so it might not remove it completely, and no promises that it will work right, since the drawer depends heavily on it. It should give you a start though.

**Comment by bennygenish** [comment]
Open` \res\values\dimens.xml`
Change from

```xml
<dimen name="dynamic_grid_hotseat_height">88.0dip</dimen>
```

To:  
```xml
<dimen name="dynamic_grid_hotseat_height">0dp</dimen>
```

Done.
